#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test1
    username: root
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    
    
#项目配置
server:
  port: 8081
  servlet:
    context-path: 
    
    
#指定mybatis映射文件
mybatis:
  mapper-locations: classpath*:mapper/*.xml    
  type-aliases-package: com.example.demo.model
  
